//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientNode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientNode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;host name=&quot;host1&quot;&gt;
        ///	&lt;host-topological-ip&gt;192.168.1.2&lt;/host-topological-ip&gt;
        ///	&lt;assigned-router-topological-ip&gt;192.168.1.1&lt;/assigned-router-topological-ip&gt;
        ///	&lt;port&gt;60000&lt;/port&gt;
        ///&lt;/host&gt;.
        /// </summary>
        public static string h1 {
            get {
                return ResourceManager.GetString("h1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;host name=&quot;host2&quot;&gt;
        ///	&lt;host-topological-ip&gt;&lt;/host-topological-ip&gt;
        ///	&lt;assigned-router-topological-ip&gt;&lt;/assigned-router-topological-ip&gt;
        ///	&lt;port&gt;60002&lt;/port&gt;
        ///&lt;/host&gt;.
        /// </summary>
        public static string h2 {
            get {
                return ResourceManager.GetString("h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;host name=&quot;host3&quot;&gt;
        ///	&lt;host-topological-ip&gt;&lt;/host-topological-ip&gt;
        ///	&lt;assigned-router-topological-ip&gt;&lt;/assigned-router-topological-ip&gt;
        ///	&lt;port&gt;60003&lt;/port&gt;
        ///&lt;/host&gt;.
        /// </summary>
        public static string h3 {
            get {
                return ResourceManager.GetString("h3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;host name=&quot;host4&quot;&gt;
        ///	&lt;host-topological-ip&gt;&lt;/host-topological-ip&gt;
        ///	&lt;assigned-router-topological-ip&gt;&lt;/assigned-router-topological-ip&gt;
        ///	&lt;port&gt;60004&lt;/port&gt;
        ///&lt;/host&gt;.
        /// </summary>
        public static string h4 {
            get {
                return ResourceManager.GetString("h4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;host name=&quot;host5&quot;&gt;
        ///	&lt;host-topological-ip&gt;&lt;/host-topological-ip&gt;
        ///	&lt;assigned-router-topological-ip&gt;&lt;/assigned-router-topological-ip&gt;
        ///	&lt;port&gt;60005&lt;/port&gt;
        ///&lt;/host&gt;.
        /// </summary>
        public static string h5 {
            get {
                return ResourceManager.GetString("h5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;config&gt;
        ///	&lt;hosts&gt;
        ///	
        ///		&lt;host id=&quot;1&quot;&gt;
        ///			&lt;host-ip&gt;160.0.0.2&lt;/host-ip&gt;
        ///			&lt;host-port&gt;50000&lt;/host-port&gt;
        ///			
        ///		&lt;/host&gt;
        ///	
        ///		&lt;host id=&quot;2&quot;&gt;
        ///			&lt;host-ip&gt;160.0.1.2&lt;/host-ip&gt;
        ///			&lt;host-port&gt;50000&lt;/host-port&gt;
        ///		&lt;/host&gt;
        ///	
        ///		&lt;host id=&quot;3&quot;&gt;
        ///			&lt;host-ip&gt;160.0.1.3&lt;/host-ip&gt;
        ///			&lt;host-port&gt;50000&lt;/host-port&gt;
        ///		&lt;/host&gt;
        ///	
        ///		&lt;host id=&quot;4&quot;&gt;
        ///			&lt;host-ip&gt;160.0.2.2&lt;/host-ip&gt;
        ///			&lt;host-port&gt;50000&lt;/host-port&gt;
        ///		&lt;/host&gt;
        ///	
        ///		&lt;host id=&quot;5&quot;&gt;
        ///			&lt;host-ip&gt;160.0.2.3&lt;/host-ip&gt;
        ///			&lt;h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string tsst_config {
            get {
                return ResourceManager.GetString("tsst_config", resourceCulture);
            }
        }
    }
}
